#!/bin/sh
cd /usr/src/packages/sim
#exec >> refresh.log 2>> refresh.err
#date
#date 1>&2
if [ `id -u` -ne 502 ]; then
	echo Incorrect user ID: `id`
	exit 1;
fi
EC=0
if ! lockfile -r 0 update.lock; then
	echo Failed to obtain lock, aborting.
	exit 1;
fi
trap "rm -f update.lock" SIGHUP SIGINT SIGQUIT SIGTERM EXIT

export http_proxy=http://localhost:3128/
#export http_proxy=http://rps:3129/

MODE="$1"
if [ "$MODE" = "auto" ]; then
	MODE=`perl -le 'print 2<24*-M $ARGV[0]?"full":"update"' ~/doujin/.lastfullupdate`
fi;
if [ "$MODE" = "update" ]; then
	echo Quick update

	./danbooru-change danbooru   || let EC=$EC+2
	./danbooru-change konachan   || let EC=$EC+2
	./danbooru-change moe.imouto || let EC=$EC+2
	./danbooru-change 4scrape    || let EC=$EC+2
	./danbooru-change sankaku    || let EC=$EC+2
	#./danbooru-change kurankuran || let EC=$EC+2

	touch ~/doujin/.lastquickupdate ~/doujin/.lastupdate
	exit $EC
elif [ "$MODE" = "full" ]; then
	echo Full update

	./danbooru-change danbooru   full  || let EC=$EC+2
	./danbooru-change konachan   full  || let EC=$EC+2
	./danbooru-change moe.imouto full  || let EC=$EC+2
	./danbooru-change 4scrape          || let EC=$EC+2
	./danbooru-change sankaku    full  || let EC=$EC+2
	#./danbooru-change kurankuran full  || let EC=$EC+2

	touch ~/doujin/.lastfullupdate ~/doujin/.lastupdate
	exit $EC
elif [ "$MODE" != "restart" ]; then
	echo Unknown mode, run as $0 auto/update/full/restart
	exit 1;
fi;

SCREEN=iqdbOne
OTHER=iqdbTwo
screen -ls|grep iqdb
if screen -ls|grep $SCREEN &> /dev/null; then
	SCREEN=iqdbTwo
	OTHER=iqdbOne
fi;
PID=`screen -ls|grep $OTHER|perl -lne 'print $1 if /(\d+)/'`
echo "Starting screen $SCREEN (other $OTHER pid $PID)"
screen -dmS $SCREEN ~/bin/iqdb.server listen2 5566 -r `./def-dbs`
echo Waiting for $PID to exit.
COUNT=0
while [ -n "$PID" -a -d /proc/$PID ]; do
	let COUNT=$COUNT+1
	if [ $COUNT -gt 120 ]; then echo "Waited too long, aborting."; exit 1; fi;
	sleep 2;
done;
echo Waited $COUNT*2 seconds.
COUNT=0
while ! echo  -e "ping me\ndone now\n"|nc localhost 5566; do
	let COUNT=$COUNT+1
	if [ $COUNT -gt 3 ]; then echo "Waited too long, aborting."; exit 1; fi;
	sleep 5;
done;
touch ~/doujin/.lastrestart
exit $EC
